#!/bin/zsh
# brain-in-a-box weekly lint (launchd: com.<user>.gbrain-lint, Monday 08:00).
#
# The nightly MAINTAINS the brain (sync/dream) but writes to a log nobody
# reads — a silently-failing maintenance job looks exactly like a healthy one.
# This job VERIFIES and surfaces the result where it gets read:
#   - <vault>/Profile/lint.md  : full report (replaced every run)
#   - <vault>/Profile/memory.md : one-line verdict between <!-- LINT --> markers
# No LLM pass — pure CLI, immune to transient API failures. Read-only on the
# vault except those two files.

export PATH="$HOME/.bun/bin:/opt/homebrew/bin:/usr/bin:/bin"
GBRAIN="$HOME/.bun/bin/gbrain"
VAULT="$HOME/Documents/Brain"
LOG="$HOME/.gbrain/lint.log"
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT

# doctor is cwd-sensitive (its resolver check targets the vault's skills)
cd "$VAULT" || exit 1

echo "===== $(date '+%F %T') lint start =====" >> "$LOG"

# last week's report quotes raw issues → lint would recount them; remove it
# before the pass (regenerated at the end of the run)
rm -f "$VAULT/Profile/lint.md"

"$GBRAIN" doctor --fast --json           > "$TMP/doctor.json"   2>>"$LOG"
"$GBRAIN" lint "$VAULT"                  > "$TMP/lint.txt"      2>&1
"$GBRAIN" orphans --count                > "$TMP/orphans.txt"   2>>"$LOG"
"$GBRAIN" anomalies --since 7d           > "$TMP/anomalies.txt" 2>&1
"$GBRAIN" check-backlinks check "$VAULT" > "$TMP/backlinks.txt" 2>&1
"$GBRAIN" stats                          > "$TMP/stats.txt"     2>&1
grep -E 'nightly (start|done)' "$HOME/.gbrain/nightly.log" 2>/dev/null | tail -6 > "$TMP/nightly.txt"

python3 - "$TMP" "$VAULT" <<'PY' >> "$LOG" 2>&1
import json, re, sys
from datetime import datetime
from pathlib import Path

tmp, vault = Path(sys.argv[1]), Path(sys.argv[2])
today = datetime.now().strftime("%Y-%m-%d")

def read(name):
    p = tmp / name
    return p.read_text(errors="replace") if p.exists() else ""

# --- doctor ---
doctor_status, doctor_score, doctor_fails = "unknown", "?", []
try:
    d = json.loads(read("doctor.json"))
    doctor_status = d.get("status", "unknown")
    doctor_score = d.get("health_score", "?")
    doctor_fails = [c["name"] for c in d.get("checks", []) if c.get("status") == "fail"]
except Exception:
    pass

# --- lint ---
lint_txt = read("lint.txt")
m = re.search(r"(\d+) pages scanned\. (\d+) issue\(s\)", lint_txt)
lint_pages, lint_issues = (int(m.group(1)), int(m.group(2))) if m else (0, -1)

# --- orphans ---
m = re.search(r"^(\d+)$", read("orphans.txt"), re.M)
orphans = int(m.group(1)) if m else -1

# --- anomalies / backlinks ---
anom_txt = read("anomalies.txt").strip()
anomalies_clean = "(no anomalies" in anom_txt or not anom_txt
back_txt = read("backlinks.txt")
backlinks_clean = "No missing back-links" in back_txt

# --- nightly freshness ---
nightly_txt = read("nightly.txt")
last_done, nightly_age_h = None, None
for line in nightly_txt.splitlines():
    m = re.search(r"(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) nightly done", line)
    if m:
        last_done = m.group(1)
if last_done:
    nightly_age_h = (datetime.now() - datetime.strptime(last_done, "%Y-%m-%d %H:%M:%S")).total_seconds() / 3600

# --- stats ---
stats_txt = read("stats.txt").strip()
m = re.search(r"Links:\s+(\d+)", stats_txt)
links = int(m.group(1)) if m else -1
m = re.search(r"Pages:\s+(\d+)", stats_txt)
db_pages = int(m.group(1)) if m else -1

# --- verdict ---
red = (nightly_age_h is None or nightly_age_h > 48) or (isinstance(doctor_score, int) and doctor_score < 50) or lint_issues < 0
orange = doctor_status != "healthy" or lint_issues > 0 or not backlinks_clean or not anomalies_clean
verdict = "🔴" if red else ("🟠" if orange else "🟢")

reasons = []
if nightly_age_h is None:
    reasons.append("nightly: no 'done' entry found in the log")
elif nightly_age_h > 48:
    reasons.append(f"nightly DEAD for {nightly_age_h:.0f}h")
else:
    reasons.append(f"nightly OK (last run {last_done})")
reasons.append(f"doctor {doctor_status} ({doctor_score}/100" + (f", fail: {', '.join(doctor_fails)}" if doctor_fails else "") + ")")
if lint_issues >= 0:
    reasons.append(f"{lint_issues} frontmatter/artifact issue(s) across {lint_pages} pages")
reasons.append(f"{orphans} orphan pages / {db_pages} in DB, {links} links")
if not anomalies_clean:
    reasons.append("statistical anomalies detected (see report)")
if not backlinks_clean:
    reasons.append("missing back-links (see report)")

summary = " · ".join(reasons)

# --- full report -> Profile/lint.md ---
report = f"""---
title: Weekly brain lint
created: {today}
type: report
---

# Weekly lint — {today} {verdict}

{summary}

Generated by engine/nightly/gbrain-lint.sh (launchd, Monday 08:00).
Raw output of each pass below.

## doctor --fast
```json
{read("doctor.json").strip()}
```

## lint (frontmatter, LLM artifacts, placeholder dates)
Bulk-fixable: `gbrain lint <vault> --fix`
```
{lint_txt.strip()[-4000:]}
```

## anomalies (7 days)
```
{anom_txt or "(empty)"}
```

## back-links
```
{back_txt.strip()[-1500:]}
```

## stats
```
{stats_txt}
```

## nightly (recent runs)
```
{nightly_txt.strip() or "(nightly log not found)"}
```
"""
(vault / "Profile" / "lint.md").write_text(report)

# --- verdict block -> Profile/memory.md (between markers, idempotent) ---
mem_path = vault / "Profile" / "memory.md"
block = (
    "<!-- LINT:BEGIN -->\n"
    f"> **🧹 Weekly lint {today} {verdict}** — {summary}. Detail: `Profile/lint.md`.\n"
    "<!-- LINT:END -->"
)
mem = mem_path.read_text() if mem_path.exists() else "# Memory\n"
if "<!-- LINT:BEGIN -->" in mem:
    mem = re.sub(r"<!-- LINT:BEGIN -->.*?<!-- LINT:END -->", block, mem, flags=re.S)
else:
    lines = mem.splitlines(keepends=True)
    lines.insert(min(2, len(lines)), "\n" + block + "\n")
    mem = "".join(lines)
mem_path.write_text(mem)

print(f"lint {verdict} — {summary}")
PY

echo "===== $(date '+%F %T') lint done =====" >> "$LOG"
